# Generated by Django 5.1.1 on 2024-09-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='img',
            field=models.CharField(default='default', max_length=500),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='ready',
            field=models.CharField(max_length=255),
        ),
    ]
