# Generated by Django 5.1.1 on 2024-09-04 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_foodentry_img_alter_foodentry_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='img',
        ),
    ]
