# Generated by Django 5.1.1 on 2024-10-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_foodentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='img',
            field=models.CharField(max_length=1000, verbose_name='Menu Image'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='price',
            field=models.IntegerField(verbose_name='Price (Rp.)'),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='ready',
            field=models.CharField(max_length=255, verbose_name='Ready?'),
        ),
    ]
